#!/bin/bash

unset DEBIAN_FRONTEND

repo=https://github.com/COMP1511UNSW/course_materials.git
repo_dir=private
git_clone_command="git clone $repo private"
mount_point=/root

cd $mount_point || exit 1
export PATH=$PATH:/home/cs1511/public_html/18s1//scripts:.



if test ! -d "$mount_point/$repo_dir/.git/"
then 
    cat <<eof
    
$mount_point/$repo_dir/.git/ does not exist.

eof

echo -n "clone repository? [no] "

	read answer
	case "$answer" in
	[yY]*)
		echo "$git_clone_command"
		$git_clone_command
		;;
	*)
		cat <<eof
	
Your repo should be in a directory named private.
Docker should be run with the parent of this directory mounted on /root
and port 5000 exposed.

For example if your repo is /home/chris/website/private run
docker run -it -v /home/chris/website/:$mount_point -p 5000:5000 comp1511/webpages

eof
	esac
else
	cd $mount_point/$repo_dir/
	echo -n "git pull?"
	read answer
	case "$answer" in
	[yY]*)
		git pull
		;;
	esac
fi

if test -d $mount_point/$repo_dir/.git/
then
	cd $mount_point/$repo_dir/
	echo scripts/build
	scripts/build
	echo "while sleep 1;do flask/webpages.py; done &"
	while sleep 1;do flask/webpages.py; done &
fi
bash -l
