#!/bin/bash
#set -x
unset DEBIAN_FRONTEND

cd /root || exit 1
export PATH=$PATH:/home/cs1511/public_html18s1//scripts:.

if test ! -d private
then 
    cat <<eof
    
Directory /root/private not found/
You need to clone the repo into the directory private
and mount the parent directory of the repo on /root for example:

mkdir -m 700 website
cd website
git clone  git@github.com:COMP1511UNSW/course_materials.git private
docker run -it -v `pwd`:/root -p 5000:5000 comp1511/webpages
eof
	exit 1
fi

cd private
scripts/build
while sleep 1;do flask/webpages.py; done
